[project]
name = "example4mujoco"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapy>=1.2.4",
    "mujoco>=3.3.5",
]
